# Generated by Django 4.1.6 on 2023-02-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=250)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('lancamento', models.DateTimeField()),
                ('descrição', models.TextField()),
                ('genero', models.IntegerField(choices=[(0, 'Terror'), (1, 'Animacao'), (2, 'Suspense'), (3, 'Acao')], null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastrofilmes.autor')),
            ],
        ),
    ]
