# Generated by Django 4.1.6 on 2023-02-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrofilmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nome',
            new_name='name',
        ),
    ]
