# Generated by Django 4.1.6 on 2023-02-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrofilmes', '0002_rename_nome_autor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='tipoautor',
            field=models.IntegerField(choices=[(0, 'Filmes'), (1, 'Livros'), (3, 'Filmeslivros')], null=True),
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('publicacao', models.DateTimeField()),
                ('pages', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastrofilmes.autor')),
            ],
        ),
    ]
