# Generated by Django 4.1.6 on 2023-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrofilmes', '0003_autor_tipoautor_livros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='tipoautor',
            field=models.TextField(choices=[('filmes', 'Filmes'), ('livros', 'Livros'), ('filmeslivros', 'Filmeslivros')], null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.TextField(choices=[('terror', 'Terror'), ('animação', 'Animacao'), ('suspense', 'Suspense'), ('ação', 'Acao')], null=True),
        ),
    ]
